name: .NET Tests

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    # WPF requiere Windows, Linux (ubuntu-latest) fallará siempre
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        # Apuntamos a la carpeta donde está el .sln realmente
        run: dotnet restore MusRoyalePC/MusRoyalePC.sln

      - name: Build
        run: dotnet build MusRoyalePC/MusRoyalePC.sln --no-restore --configuration Debug

      - name: Run Tests
        # Ejecutamos los tests a través de la solución
        run: dotnet test MusRoyalePC/MusRoyalePC.sln --no-build --verbosity normal