name: .NET Tests

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    # IMPORTANTE: WPF requiere Windows para compilar y ejecutar tests
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        # Si el archivo .sln no está en la raíz, ajusta la ruta
        run: dotnet restore MusRoyalePC.sln

      - name: Build
        run: dotnet build MusRoyalePC.sln --no-restore --configuration Debug

      - name: Run Tests
        # Ejecuta los tests del proyecto específico de tests
        run: dotnet test MusRoyalePC.sln --no-build --verbosity normal