name: .NET Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore MusRoyalePC.sln

      - name: Build
        run: dotnet build MusRoyalePC.sln --no-restore --configuration Debug

      - name: Run Tests
        run: dotnet test MusRoyalePC.sln --no-build --logger "trx"
